name: vdom_benchmark
description: A sample web application
dependencies:
  browser: any
  charted: any
  vdom: '>=0.4.0'
  liquid:
    git: git@github.com:localvoid/liquid.git
dependency_overrides:
  vdom:
    path: ../vdom
  liquid:
    path: ../liquid
