name: vdom_benchmark
description: A sample web application
dependencies:
  browser: any
  charted: any
  vdom:
    git://github.com/localvoid/vdom.git
  vcomponent:
    git://github.com/localvoid/vcomponent.git
